"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {Mountain,MapPinned,Camera,ArrowUpRight,Route,Users,CalendarDays,MapPin,Clock,Navigation,ArrowLeft,ArrowRight,Car,TrainFront,Footprints,Plane,BedDouble,ExternalLink,ChevronRight,Images,X,Compass} from "lucide-react";
import {Tabs,TabsList,TabsTrigger,TabsContent} from "@/components/ui/tabs";
import {Sheet,SheetContent,SheetTitle,SheetDescription} from "@/components/ui/sheet";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {Toaster} from "@/components/ui/sonner";
import {days,places,placeById,tripDaysFor,modeLabel,stayName,dayPlaceIds,type Place,type TripDay} from "@/lib/trip-data";
import {photoCredits} from "@/lib/photo-credits";
import TripMap from "./trip-map";
import DrivingSummary from "./driving-summary";
import PhotoAlbum,{PRIVATE_ALBUM_URL,type Photo} from "./photo-album";
const modeIcon={flight:Plane,rail:TrainFront,city:Footprints,drive:Car,hike:Footprints};
const navLink=(p:Place)=>`https://uri.amap.com/search?keyword=${encodeURIComponent(p.navigation||p.name.replace(" · 远眺","").replace("（日瓦）","")+(p.id==="shangrila"?" 稻城县":""))}&src=chuanxi-autumn&callnative=1`;
function Scenery({place,className="",lazy=true}:{place:Place;className?:string;lazy?:boolean}){const [failed,setFailed]=useState(false);const credit=place.image?photoCredits[place.image]:undefined;return credit&&!failed?<img className={className} src={`${import.meta.env.BASE_URL}scenery/${place.image}.jpg`} alt={place.photoLabel||credit.subject} loading={lazy?"lazy":"eager"} onError={()=>setFailed(true)}/>:<div className={`scenery-text ${className}`}><span>{place.region}</span><strong>{place.name}</strong><small>{place.tags.slice(0,2).join(" / ")}</small></div>;}
function DayMeta({day}:{day:TripDay}){const Icon=modeIcon[day.mode];return <div className="day-meta"><span><Icon size={16}/>{modeLabel[day.mode]}</span><span><BedDouble size={16}/>{stayName(day)}</span></div>;}
export default function TripApp({signedIn}:{signedIn:boolean}){
 const [view,setView]=useState("map");const [dayId,setDayId]=useState(0);const [placeId,setPlaceId]=useState<string|null>(null);const [detailTab,setDetailTab]=useState("intro");const [photos,setPhotos]=useState<Photo[]>([]);const [loading,setLoading]=useState(false);const [photoError,setPhotoError]=useState("");const [allDays,setAllDays]=useState(false);const [creditsOpen,setCreditsOpen]=useState(false);
 const loadPhotos=useCallback(async()=>{},[]);
 const counts=useMemo(()=>photos.reduce((a,p)=>{a[p.placeId]=(a[p.placeId]||0)+1;return a},{} as Record<string,number>),[photos]);
 const openPlace=useCallback((id:string,tab="intro")=>{if(!placeById[id])return;setPlaceId(id);setDetailTab(tab)},[]);
 const selectDay=useCallback((id:number)=>{setDayId(id);setView("map");setPlaceId(null)},[]);
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const defs=[{name:"read_travel_itinerary",title:"读取旅行行程",description:"读取2026年9月25日至10月7日已经确认的旅行行程。",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({days:days.map(d=>({day:d.id,date:d.date,title:d.title,stay:stayName(d),places:dayPlaceIds(d).map(id=>({id,name:placeById[id].name})),note:d.note}))})},{name:"open_travel_day",title:"在地图查看一天",description:"切换到指定日期的旅行路线，仅改变地图显示，不修改已确认行程。",inputSchema:{type:"object",properties:{day:{type:"integer",minimum:1,maximum:days.length}},required:["day"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const d=(input as {day?:unknown})?.day;if(typeof d!=="number"||!Number.isInteger(d)||d<1||d>days.length)throw new Error(`day须为1到${days.length}的整数`);selectDay(d);await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {day:d,title:days[d-1].title,view:"map"}}},{name:"open_place_album",title:"打开地点相册",description:"打开指定地点的私人相册入口说明，不自动打开外部页面。",inputSchema:{type:"object",properties:{placeId:{type:"string",enum:places.map(p=>p.id)}},required:["placeId"],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const id=(input as {placeId?:unknown})?.placeId;if(typeof id!=="string"||!placeById[id])throw new Error("地点不存在");openPlace(id,"photos");await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));return {placeId:id,name:placeById[id].name,tab:"photos"}}}];for(const def of defs){try{Promise.resolve(context.registerTool(def,{signal:life.signal})).catch(()=>{})}catch{}}return()=>life.abort()},[selectDay,openPlace]);
 const day=days.find(d=>d.id===dayId);const selected=placeId?placeById[placeId]:null;const feature=day?placeById[day.stops.find(id=>placeById[id].image&&!["chengdu","xinduqiao"].includes(id))||day.stops[0]]:placeById.jiuzhaigou;
 const albums=places.filter(p=>!["交通","出发地","住宿"].includes(p.category));
 return <Tabs value={view} onValueChange={setView} className="trip-shell"><header className="topbar"><button className="brand" onClick={()=>{setView("map");setDayId(0)}} aria-label="返回旅行地图"><span className="brand-mark"><Mountain/></span><strong>一路向山<span>川西 · 2026</span></strong></button><TabsList className="top-nav" variant="line"><TabsTrigger value="map"><MapPinned size={17}/>旅行地图</TabsTrigger><TabsTrigger value="itinerary"><CalendarDays size={17}/>整体行程</TabsTrigger><TabsTrigger value="albums"><Camera size={17}/>旅行相册</TabsTrigger></TabsList><span className="private-label">09.25 — 10.07 <i/> 公开旅行地图</span></header>
 <TabsContent value="map" className="workspace map-tab"><aside className="itinerary"><div className="trip-heading"><p className="eyebrow">AUTUMN JOURNEY / 2026</p><h1>把秋天，<br/>交给山野。</h1><p>重庆的灯火，成都的茶，川西的山。</p><div className="trip-stats"><span><CalendarDays size={16}/>{days.length} 天</span><span><Users size={16}/>2 位司机</span><span><MapPin size={16}/>{places.length} 站</span></div></div><div className="list-heading"><b>我们的行程</b><button onClick={()=>setDayId(0)}>查看总览 <ArrowUpRight size={13}/></button></div><div className="day-list">{days.map(d=><button key={d.id} className={`day-button ${dayId===d.id?"selected":""}`} onClick={()=>setDayId(d.id)}><span className="day-number">{String(d.id).padStart(2,"0")}</span><span><small>{d.date} · {d.weekday}</small><strong>{d.title}</strong></span><ArrowUpRight size={16}/></button>)}</div><div className="sidebar-footer"><Compass size={14}/><span>顺着地图，慢慢出发</span><button onClick={()=>setCreditsOpen(true)}>关于</button></div></aside><section className="map-workspace"><TripMap dayId={dayId} onPlace={openPlace} counts={counts} onOverview={()=>setDayId(0)}/><button className="featured-place" onClick={()=>openPlace(feature.id)}><div className="feature-image"><Scenery place={feature} lazy={false}/><span className="image-badge">风景参考</span></div><div className="feature-copy"><span className="eyebrow">{day?`DAY ${String(day.id).padStart(2,"0")}`:"沿途的一站"}</span><h3>{feature.name}<ArrowUpRight size={20}/></h3><p>{feature.tags.slice(0,3).join(" · ")}</p><span className="feature-action">看景点与照片 <ChevronRight size={14}/></span></div></button><div className="map-bottom"><div className="bottom-icon">{day?<span>{String(day.id).padStart(2,"0")}</span>:<Route size={23}/>}</div><div className="bottom-copy"><b>{day?`${day.date} ${day.weekday} · ${day.subtitle}`:`${days.length}天，从城市走到雪山脚下`}</b>{day&&day.id>=6&&day.id<=12?<DrivingSummary day={day} onPlace={openPlace} compact/>:<p>{day?`住 ${stayName(day)} · ${modeLabel[day.mode]}`:"重庆 → 成都 → 九寨沟 → 川西环线"}</p>}{day&&<div className="stop-chips">{dayPlaceIds(day).filter(id=>!["nanjing","jiangbei","chengdudong","huanglong"].includes(id)).map(id=><button key={id} onClick={()=>openPlace(id)}>{placeById[id].name}{day.optional?.includes(id)?"（可选）":""}</button>)}</div>}</div><button className="bottom-detail" onClick={()=>setAllDays(true)}>{day?"当天安排":"查看行程"}<ArrowUpRight size={17}/></button></div></section></TabsContent>
 <TabsContent value="itinerary" className="page-tab"><div className="page-heading"><div><p className="eyebrow">OUR DAYS ON THE ROAD</p><h1>我们的 {days.length} 天</h1><p>2026年9月25日—10月7日 · 两位司机 · 重庆、成都、九寨沟与川西</p></div><button className="subtle-button" onClick={()=>{setView("map");setDayId(0)}}><MapPinned size={18}/>回到地图</button></div><div className="itinerary-cards">{days.map(d=>{const img=placeById[d.stops.find(id=>placeById[id].image&&!["chengdu","xinduqiao"].includes(id))||d.stops[0]];return <article className="day-card" key={d.id}><button className="day-card-image" onClick={()=>selectDay(d.id)}><Scenery place={img}/><span>DAY {String(d.id).padStart(2,"0")}</span></button><div className="day-card-content"><div className="day-card-title"><div><small>{d.date} / {d.weekday}</small><h2>{d.title}</h2></div><button aria-label={`地图查看第${d.id}天`} onClick={()=>selectDay(d.id)}><ArrowUpRight size={21}/></button></div><DayMeta day={d}/><DrivingSummary day={d} onPlace={openPlace}/><div className="schedule-parts">{d.parts.map(x=><div key={x.period}><span>{x.period}</span><p>{x.text}</p></div>)}</div><div className="itinerary-place-links">{dayPlaceIds(d).map(id=><button key={id} onClick={()=>openPlace(id)}>{placeById[id].name}<ChevronRight size={12}/></button>)}</div><p className="day-note">{d.note}</p></div></article>})}</div><footer className="page-footer">行程已按本次确认整理 · 车次、票务、道路与景区开放以出发前信息为准 <button onClick={()=>setCreditsOpen(true)}>资料与照片来源</button></footer></TabsContent>
 <TabsContent value="albums" className="page-tab"><div className="page-heading"><div><p className="eyebrow">OUR TRAVEL JOURNAL</p><h1>把路上的瞬间，留在地图里。</h1><p>{photos.length?`已经收藏 ${photos.length} 张照片，散落在 ${Object.keys(counts).length} 个地点。`:"每一站都留好了相册入口。上传和查看旅行照片，请进入原来的私人相册。"}</p></div><a className="primary-button" href={PRIVATE_ALBUM_URL} target="_blank" rel="noreferrer"><Camera size={18}/>打开私人相册<ExternalLink size={16}/></a></div>{photoError&&<div className="error-inline">{photoError}<button onClick={()=>void loadPhotos()}>重新加载</button></div>}<div className="album-cards">{albums.map(p=>{const cover=photos.find(x=>x.placeId===p.id);return <button className="album-card" key={p.id} onClick={()=>openPlace(p.id,"photos")}><div className="album-cover">{cover?<img src={cover.url} alt={cover.caption||p.name} loading="lazy"/>:<Scenery place={p}/>}<span className="album-count"><Camera size={14}/>私人相册入口</span>{!cover&&<span className="album-empty-label">风景参考 · 相册需登录</span>}</div><div className="album-card-name"><div><small>{p.region}</small><h2>{p.name}</h2></div><ArrowUpRight size={20}/></div></button>})}</div><footer className="page-footer">这里展示风景参考照。旅行照片保存在私人相册，不会自动公开到这个网站。<button onClick={()=>setCreditsOpen(true)}>照片来源</button></footer></TabsContent>
 <Sheet open={!!selected} onOpenChange={open=>{if(!open)setPlaceId(null)}}><SheetContent className="place-sheet" showCloseButton={false}>{selected&&<><div className="place-hero"><Scenery key={selected.id} place={selected} lazy={false}/><button className="sheet-back" onClick={()=>setPlaceId(null)} aria-label="关闭景点详情"><X size={21}/></button><span className="image-badge">{selected.image?"风景参考":"沿途地点"}</span></div><div className="place-title"><span className="eyebrow">{selected.region}</span><SheetTitle>{selected.name}</SheetTitle><SheetDescription>{selected.tags.join(" · ")}</SheetDescription><div className="visit-days">{tripDaysFor(selected.id).map(d=><button key={d.id} onClick={()=>selectDay(d.id)}>{d.date}<ArrowUpRight size={12}/></button>)}</div></div><Tabs value={detailTab} onValueChange={setDetailTab} className="detail-tabs"><TabsList className="detail-tabs-list" variant="line"><TabsTrigger value="intro">{selected.category==="住宿"?"住宿信息":"风景与特色"}</TabsTrigger><TabsTrigger value="photos"><Camera size={16}/>旅行相册</TabsTrigger></TabsList><TabsContent value="intro" className="detail-body"><p className="place-intro">{selected.intro}</p><div className="place-facts"><span><Clock size={17}/>{selected.time}</span>{selected.altitude&&<span><Mountain size={17}/>{selected.altitude}</span>}</div><h3>{selected.category==="住宿"?"位置与入住":"在这里，看什么"}</h3><ul className="highlights">{selected.highlights.map(h=><li key={h}>{h}</li>)}</ul><div className="travel-tip"><h3><Route size={17}/>我们的安排</h3><p>{selected.tip}</p></div><div className="place-buttons"><a className="primary-button" href={navLink(selected)} target="_blank" rel="noreferrer"><Navigation size={17}/>在高德地图查找</a><button className="subtle-button" onClick={()=>setDetailTab("photos")}><Camera size={17}/>打开旅行相册</button></div><p className="location-note">{selected.navigationPosition&&selected.category!=="住宿"?`自驾定位：${selected.navigation||selected.name}。景区内部交通、步行及现场停车安排另行确认。`:"地图点位用于了解游览范围。实际入口、停车点和步道请按导航及现场指引确认。"}</p>{selected.source&&<a href={selected.source} target="_blank" rel="noreferrer" className="source-link">{selected.category==="住宿"?"高德酒店位置":"景点参考信息"} <ExternalLink size={13}/></a>}{selected.image&&photoCredits[selected.image]&&<div className="photo-credit"><b>{selected.photoLabel||photoCredits[selected.image].subject}</b><span>参考照非出行当日实景 · {photoCredits[selected.image].artist}</span><a href={photoCredits[selected.image].source} target="_blank" rel="noreferrer">照片原始来源</a><a href={photoCredits[selected.image].license_url||photoCredits[selected.image].source} target="_blank" rel="noreferrer">{photoCredits[selected.image].license}</a></div>}</TabsContent><TabsContent value="photos" className="detail-body"><PhotoAlbum key={selected.id} placeId={selected.id} placeName={selected.name} photos={photos.filter(p=>p.placeId===selected.id)} signedIn={signedIn} onChange={()=>void loadPhotos()} error={photoError} loading={loading}/></TabsContent></Tabs></>}</SheetContent></Sheet>
 <Dialog open={allDays} onOpenChange={setAllDays}><DialogContent className="day-dialog"><DialogTitle>{day?`${day.date} · ${day.title}`:`${days.length}日行程总览`}</DialogTitle><DialogDescription>{day?day.subtitle:"点选一天，在地图上查看路线与景点。"}</DialogDescription>{day?<><DayMeta day={day}/><DrivingSummary day={day} onPlace={openPlace}/><div className="schedule-parts">{day.parts.map(x=><div key={x.period}><span>{x.period}</span><p>{x.text}</p></div>)}</div><p className="day-note">{day.note}</p><div className="day-dialog-actions"><button className="subtle-button" disabled={dayId===1} onClick={()=>setDayId(dayId-1)}><ArrowLeft size={16}/>前一天</button><button className="subtle-button" disabled={dayId===days.length} onClick={()=>setDayId(dayId+1)}>后一天<ArrowRight size={16}/></button></div></>:<div className="dialog-days">{days.map(d=><button key={d.id} onClick={()=>{selectDay(d.id);setAllDays(false)}}><span>{d.date}</span><b>{d.title}</b><ArrowUpRight size={16}/></button>)}</div>}</DialogContent></Dialog>
 <Dialog open={creditsOpen} onOpenChange={setCreditsOpen}><DialogContent className="credits-dialog"><DialogTitle>关于这份旅行手册</DialogTitle><DialogDescription>2026年9月25日—10月7日，按已经确认的行程整理。</DialogDescription><p>蓝色实线来自高德驾车规划，从前一晚酒店出发，途经已确认景点的停车或换乘入口，再到当晚酒店；里程与时间只计算自驾部分。亚丁村内住宿需乘景区观光车，自驾起终点设在游客中心停车场。其他交通虚线仅表达旅行顺序，并非实际轨迹。10月1日只去中路藏寨，10月5日走冷嘎措A线；双桥沟观光车、冷嘎措上山段均不计入自驾线。</p><p>照片为不同季节拍摄的实景参考，不代表旅行当天的天气和秋色。贡嘎星轨照片只作区域风景参考，原始来源未确认湖名为冷嘎措。</p><h3>参考照片</h3><div className="credits-list">{Object.entries(photoCredits).map(([key,c])=><div key={key}><a href={c.source} target="_blank" rel="noreferrer">{c.subject}</a><span>{c.artist} · <a href={c.license_url||c.source} target="_blank" rel="noreferrer">{c.license}</a></span></div>)}</div></DialogContent></Dialog><Toaster position="bottom-center" richColors theme="light"/></Tabs>;
}
