"use client";
import {useEffect,useRef,useState} from "react";
import type * as Leaflet from "leaflet";
import {Maximize,LocateFixed,MapPinned} from "lucide-react";
import {days,places,placeById,overviewIds,routes,type Place} from "@/lib/trip-data";
type Props={dayId:number;onPlace:(id:string)=>void;counts:Record<string,number>;onOverview:()=>void};
export default function TripMap({dayId,onPlace,counts,onOverview}:Props){
 const el=useRef<HTMLDivElement>(null);const map=useRef<Leaflet.Map|null>(null);const lib=useRef<typeof Leaflet|null>(null);const layer=useRef<Leaflet.LayerGroup|null>(null);const pick=useRef(onPlace);pick.current=onPlace;const [ready,setReady]=useState(false);const [error,setError]=useState(false);const [scope,setScope]=useState<"west"|"all">("west");
 useEffect(()=>{let disposed=false;let resize:ResizeObserver|undefined;import("leaflet").then(L=>{if(disposed||!el.current)return;lib.current=L;const m=L.map(el.current,{zoomControl:false,scrollWheelZoom:true,minZoom:4,maxZoom:17});map.current=m;const tiles=L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank">OpenStreetMap</a> contributors'}).addTo(m);let errors=0;tiles.on("tileerror",()=>{errors++;if(errors>=4)setError(true)});tiles.on("tileload",()=>setError(false));L.control.zoom({position:"topright"}).addTo(m);L.control.scale({position:"bottomleft",imperial:false}).addTo(m);layer.current=L.layerGroup().addTo(m);resize=new ResizeObserver(()=>m.invalidateSize());resize.observe(el.current);setReady(true);}).catch(()=>setError(true));return()=>{disposed=true;resize?.disconnect();map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{const L=lib.current,m=map.current,g=layer.current;if(!ready||!L||!m||!g)return;g.clearLayers();const d=days.find(x=>x.id===dayId);const ids=d?Array.from(new Set([...d.stops,...(d.optional||[])])):overviewIds;const pts=ids.map(x=>placeById[x]);const shown=dayId?routes.filter(r=>r.day===dayId):routes.filter(r=>scope==="all"||r.day>=6);
 shown.forEach(r=>{const color=r.mode==="rail"?"#c5762c":r.mode==="flight"?"#72819b":r.mode==="walk"?"#14886c":"#2c60d9";L.polyline(r.coords,{color:"#fff",weight:7,opacity:.9,interactive:false}).addTo(g);L.polyline(r.coords,{color,weight:3.5,opacity:.95,dashArray:r.mode==="drive"?undefined:r.mode==="walk"?"3 6":"8 8"}).addTo(g).on("click",()=>{const first=days[r.day-1].stops.find(id=>placeById[id].category!=="交通");if(first)pick.current(first);});});
 pts.forEach((p,i)=>{const wrapper=document.createElement("div");wrapper.className=`pin-body ${p.category==="交通"?"transit":""} ${d?.optional?.includes(p.id)?"optional":""}`;const dot=document.createElement("span");dot.className="pin-dot";dot.textContent=dayId?String(i+1):"";wrapper.appendChild(dot);const label=document.createElement("span");label.className="pin-name";label.textContent=p.name.replace(" · 双桥沟","").replace(" · 远眺","");wrapper.appendChild(label);if(counts[p.id]){const c=document.createElement("span");c.className="pin-count";c.textContent=String(counts[p.id]);wrapper.appendChild(c);}const marker=L.marker([p.lat,p.lng],{title:`查看${p.name}，${counts[p.id]||0}张旅行照片`,keyboard:true,icon:L.divIcon({html:wrapper,className:"travel-pin",iconSize:[30,30],iconAnchor:[15,15]})}).addTo(g);marker.on("click",()=>pick.current(p.id));});
 const bounds=dayId?L.latLngBounds(pts.map(p=>[p.lat,p.lng] as [number,number])):scope==="west"?L.latLngBounds([[28.28,99.99],[31.25,104.19]]):L.latLngBounds(places.filter(p=>["nanjing",...overviewIds].includes(p.id)).map(p=>[p.lat,p.lng] as [number,number]));const narrow=m.getSize().x<600;m.fitBounds(bounds,{paddingTopLeft:narrow?[40,95]:[65,155],paddingBottomRight:narrow?[40,125]:[240,140],maxZoom:dayId?(pts.length<=2?16:13):8,animate:true,duration:.7});
 },[ready,dayId,scope,counts]);
 return <><div ref={el} className="map-canvas" aria-label="可缩放的旅行地图，点选地点查看介绍与照片"/><div className="map-heading"><span className="eyebrow">{dayId?`DAY ${String(dayId).padStart(2,"0")} / ${days.length}`:scope==="west"?"WESTERN SICHUAN":"OUR AUTUMN JOURNEY"}</span><h2>{dayId?days[dayId-1].title:scope==="west"?"川西，一路向山":`从南京出发的${days.length}天`}</h2><p>{dayId?days[dayId-1].subtitle:"点开地图上的地点，看风景、行程与相册。"}</p></div><div className="map-view-actions"><button onClick={()=>{setScope("west");onOverview()}}><LocateFixed size={16}/>川西环线</button><button onClick={()=>{setScope("all");onOverview()}}><Maximize size={16}/>完整旅程</button></div>{error&&<div className="map-error" role="status"><MapPinned size={18}/><span>底图暂未加载；地点与行程仍可点选。也可以从景点详情打开高德地图。</span><button onClick={()=>window.location.reload()}>重新加载</button></div>}<div className="route-key"><span><i/>自驾 / 接驳</span><span><i className="rail"/>高铁</span><span><i className="walk"/>步行</span><span className="key-note">连线为行程示意，非道路导航</span></div></>;
}
