export type Place = { gcj02?:[number,number]; navigationPosition?:[number,number]; poiId?:string; address?:string; stayNights?:string[];  id:string; name:string; region:string; lat:number; lng:number; category:string; image?:string; tags:string[]; intro:string; highlights:string[]; tip:string; time:string; altitude?:string; source?:string; navigation?:string; optional?:boolean; photoLabel?:string; };
const navigationStops:Record<string,Partial<Place>>={"siguniang":{"gcj02":[102.770249,30.978932],"navigationPosition":[102.770249,30.978932],"poiId":"B0345009VR","address":"中国熊猫大道","navigation":"四姑娘山景区-四姑娘山双桥沟停车场"},"zhonglu":{"gcj02":[101.938352,30.893901],"navigationPosition":[101.938352,30.893901],"poiId":"B0MR7LY8S9","address":"·德孜青麦villa(中路藏寨店)西北侧","navigation":"中路藏寨康波古碉楼观景台-东侧地上停车场"},"yala":{"gcj02":[101.61784629321636,30.52798226433162],"navigationPosition":[101.61784629321636,30.52798226433162],"poiId":"B0L0U1X0VM","address":"亚拉雪山观景台西北侧110米","navigation":"雅拉雪山观景台北侧地上停车场"},"moshi":{"gcj02":[101.539509,30.429251],"navigationPosition":[101.539509,30.429251],"poiId":"B0HDSC5OTA","address":"八美镇墨石公园景区内(南侧)","navigation":"墨石公园景区游客中心停车场"},"tagong":{"gcj02":[101.526487,30.32141],"navigationPosition":[101.526487,30.32141],"poiId":"B0FFG9Z1WV","address":"塔公草原内(西侧)","navigation":"塔公草原停车场"},"bends":{"gcj02":[100.874699,29.996958],"navigationPosition":[100.874699,29.996958],"poiId":"B0FFJJ4DH3","address":"G318(沪聂线)","navigation":"天路十八弯观景台"},"litang":{"gcj02":[100.268156,29.993194],"navigationPosition":[100.268156,29.993194],"poiId":"B0JDJUCBFM","address":"团结路北段68号","navigation":"勒通古镇·千户藏寨旅游景区地面停车场"},"s434":{"gcj02":[101.769363,30.187926],"navigationPosition":[101.769363,30.187926],"poiId":"B0G0YMJP0O","address":"雅拉乡","navigation":"红海子"},"lengga-a":{"gcj02":[101.701143,29.635339],"navigationPosition":[101.701143,29.635339],"poiId":"B0MUZD6JIK","address":"冷嘎措景区西南侧","navigation":"冷嘎措A线游客中心"},"lenggacuo":{"gcj02":[101.685184,29.648192]}};
const p=(id:string,name:string,region:string,lat:number,lng:number,category:string,image:string|undefined,tags:string[],intro:string,highlights:string[],tip:string,time:string,extra:Partial<Place>={}):Place=>{const resolved={...extra,...navigationStops[id]};return {id,name,region,lat:resolved.gcj02?.[1]??lat,lng:resolved.gcj02?.[0]??lng,category,image,tags,intro,highlights,tip,time,...resolved};};
export const places:Place[]=[
p("hotel-chongqing","桔子重庆观音桥酒店","重庆 · 观音桥",29.567418,106.536268,"住宿",undefined,["已订住宿","住宿转场"],"入住日期：09.25。作为相邻两天住宿转场的落脚点。",["华新街华唐路2号农垦大厦LG层","高德地点：桔子酒店(重庆观音桥店)"],"每天以酒店出入口为自驾起终点，途经当天确认的景点停车／换乘入口；出发时以高德实时导航为准。","09.25 入住",{"gcj02":[106.536268,29.567418],"navigationPosition":[106.536316,29.567287],"poiId":"B0FFIZ4387","address":"华新街华唐路2号农垦大厦LG层","stayNights":["09.25"],"source":"https://www.amap.com/place/B0FFIZ4387","navigation":"桔子酒店(重庆观音桥店)"}),
p("hotel-chengdu-west","全季成都宽窄巷子省骨科医院地铁站酒店","四川 · 成都",30.651259,104.046565,"住宿",undefined,["已订住宿","住宿转场"],"入住日期：09.26、09.27、09.29。作为相邻两天住宿转场的落脚点。",["大石东路186号(省骨科医院地铁站E2口步行340米)","高德地点：全季酒店(成都宽窄巷子省骨科医院地铁站店)"],"每天以酒店出入口为自驾起终点，途经当天确认的景点停车／换乘入口；出发时以高德实时导航为准。","09.26、09.27、09.29 入住",{"gcj02":[104.046565,30.651259],"navigationPosition":[104.046497,30.651675],"poiId":"B0G1YZS1MT","address":"大石东路186号(省骨科医院地铁站E2口步行340米)","stayNights":["09.26","09.27","09.29"],"source":"https://www.amap.com/place/B0G1YZS1MT","navigation":"全季酒店(成都宽窄巷子省骨科医院地铁站店)"}),
p("hotel-chengdu-wuhou","全季成都武侯祠酒店","四川 · 成都",30.649561,104.041571,"住宿",undefined,["已订住宿","住宿转场"],"入住日期：10.06。作为相邻两天住宿转场的落脚点。",["一环路西一段35号(省骨科医院地铁站C口步行340米)","高德地点：全季酒店(成都武侯祠店)"],"每天以酒店出入口为自驾起终点，途经当天确认的景点停车／换乘入口；出发时以高德实时导航为准。","10.06 入住",{"gcj02":[104.041571,30.649561],"navigationPosition":[104.041258,30.649388],"poiId":"B001C8P77V","address":"一环路西一段35号(省骨科医院地铁站C口步行340米)","stayNights":["10.06"],"source":"https://www.amap.com/place/B001C8P77V","navigation":"全季酒店(成都武侯祠店)"}),
p("hotel-danba","格林豪泰酒店（丹巴县店）","四川 · 丹巴",30.883351,101.9113,"住宿",undefined,["已订住宿","住宿转场"],"入住日期：09.30。作为相邻两天住宿转场的落脚点。",["章谷镇边古村干磨子1组51号","高德地点：格林豪泰酒店(丹巴县店)"],"每天以酒店出入口为自驾起终点，途经当天确认的景点停车／换乘入口；出发时以高德实时导航为准。","09.30 入住",{"gcj02":[101.9113,30.883351],"navigationPosition":[101.911203,30.883399],"poiId":"B0KKNU51CC","address":"章谷镇边古村干磨子1组51号","stayNights":["09.30"],"source":"https://www.amap.com/place/B0KKNU51CC","navigation":"格林豪泰酒店(丹巴县店)"}),
p("hotel-cangrelin","新都桥仓热林民宿（新都桥镇店）","四川 · 新都桥",30.038094,101.486565,"住宿",undefined,["已订住宿","住宿转场"],"入住日期：10.01。作为相邻两天住宿转场的落脚点。",["新都桥新一村","高德地点：新都桥仓热林民宿(新都桥镇店)"],"每天以酒店出入口为自驾起终点，途经当天确认的景点停车／换乘入口；出发时以高德实时导航为准。","10.01 入住",{"gcj02":[101.486565,30.038094],"navigationPosition":[101.486974,30.037976],"poiId":"B0H23RSAVU","address":"新都桥新一村","stayNights":["10.01"],"source":"https://www.amap.com/place/B0H23RSAVU","navigation":"新都桥仓热林民宿(新都桥镇店)"}),
p("hotel-tianlai","天籁庄园酒店（稻城亚丁游客中心店）","四川 · 稻城仁村",28.545617,100.323067,"住宿",undefined,["已订住宿","住宿转场"],"入住日期：10.02。作为相邻两天住宿转场的落脚点。",["香格里拉镇仁村3组2号附101号","高德地点：天籁庄园酒店(稻城亚丁景区店)"],"每天以酒店出入口为自驾起终点，途经当天确认的景点停车／换乘入口；出发时以高德实时导航为准。","10.02 入住",{"gcj02":[100.323067,28.545617],"navigationPosition":[100.323411,28.545739],"poiId":"B0JALS6L3D","address":"香格里拉镇仁村3组2号附101号","stayNights":["10.02"],"source":"https://www.amap.com/place/B0JALS6L3D","navigation":"天籁庄园酒店(稻城亚丁景区店)"}),
p("hotel-zhaxi","稻城亚丁扎西空墅藏文化主题酒店","四川 · 亚丁村",28.454875,100.339725,"住宿",undefined,["已订住宿","景区内接驳"],"入住日期：10.03。酒店位于亚丁景区内。",["香格里拉镇亚丁村一号站","高德地点：稻城亚丁扎西空墅藏文化主题酒店"],"位于景区内亚丁村一号站。私家车停在景区外，入住和次日出沟衔接景区观光车；10月4日出沟取车后再开始自驾。","10.03 入住",{"gcj02":[100.339725,28.454875],"navigationPosition":[100.339725,28.454875],"poiId":"B0MUUGWDJT","address":"香格里拉镇亚丁村一号站","stayNights":["10.03"],"source":"https://www.amap.com/place/B0MUUGWDJT","navigation":"稻城亚丁扎西空墅藏文化主题酒店"}),
p("hotel-ruifeng","康定瑞枫民宿（新都桥店）","四川 · 新都桥",30.078785,101.480648,"住宿",undefined,["已订住宿","住宿转场"],"入住日期：10.04、10.05。作为相邻两天住宿转场的落脚点。",["新都桥镇东俄洛二村一组25号","高德地点：康定瑞枫民宿(新都桥店)"],"每天以酒店出入口为自驾起终点，途经当天确认的景点停车／换乘入口；出发时以高德实时导航为准。","10.04、10.05 入住",{"gcj02":[101.480648,30.078785],"navigationPosition":[101.480389,30.078753],"poiId":"B0KDVMPR1I","address":"新都桥镇东俄洛二村一组25号","stayNights":["10.04","10.05"],"source":"https://www.amap.com/place/B0KDVMPR1I","navigation":"康定瑞枫民宿(新都桥店)"}),
p("yading-parking","亚丁游客中心停车场","四川 · 稻城仁村",28.536388,100.316657,"交通",undefined,["停车取车","景区接驳"],"10月3日从天籁庄园酒店开到景区外停车，再乘观光车进亚丁村；10月4日出沟后在此取车，开往新都桥。",["景区外停车","换乘观光车","连接景区内住宿与自驾"],"地图暂以亚丁景区立体停车场作为自驾衔接点，实际停车场以当天安排为准。","10.03 / 10.04",{"gcj02":[100.316657,28.536388],"navigationPosition":[100.316458,28.536428],"poiId":"B0HGV5Q8YG","address":"香格里拉镇甘孜稻城亚丁景区内(北侧)","source":"https://www.amap.com/place/B0HGV5Q8YG"}),
p("nanjing","南京出发","江苏 · 南京",32.06,118.79,"出发地",undefined,["旅程起点","飞机"],"从熟悉的城市出发，把接下来的十三天留给重庆、成都与川西。",["提前准备证件、充电宝和随身保暖层","机票时间以实际订单为准"],"行程暂按9月25日10:15抵达重庆江北机场安排。","9月25日出发"),
p("jiangbei","重庆江北机场","重庆 · 渝北",29.719,106.642,"交通",undefined,["抵达","重庆第一站"],"抵达重庆后先前往市区放行李，午餐后开始城市漫步。",["市区游览前先寄存行李","夜游船班和登船码头按订单确认"],"10:15暂按落地时间理解；航班若调整，同步压缩下午游览。","交通转场"),
p("jiefangbei","解放碑","重庆 · 渝中",29.5582,106.5754,"城市",undefined,["城市地标","步行街"],"纪念碑与高楼、步行街交织，是认识重庆中心城区的一站。沿街吃顿饭，再步行去周边看城市的高差。",["解放碑城市地标","街头小吃与街景","与魁星楼、洪崖洞一带串联"],"午后放好行李再来，第一天不用赶满。","约45—60分钟"),
p("kuixing","魁星楼","重庆 · 渝中",29.5639,106.5727,"城市",undefined,["立体重庆","高差视角"],"平台、连廊与建筑在不同高度连接，换个方向就像到了另一层城市。",["建筑与街道的垂直高差","连廊视角","与解放碑一带一起走"],"按现场开放区域通行；拍照注意来往行人。","约30分钟"),
p("cruise","两江夜游","重庆 · 两江",29.572,106.587,"夜景","chongqing",["江上视角","灯火"],"从江面回望两岸楼群、桥梁和山城灯火，和陆地步行看到的是另一种重庆。",["两岸夜景","桥梁与城市天际线","江风与灯光倒影"],"地图标注朝天门一带为示意，实际登船码头和时间以船票为准。","按所选船班",{photoLabel:"重庆洪崖洞实景 · 夜游沿岸参考"}),
p("hongya","洪崖洞","重庆 · 渝中",29.5628,106.578,"夜景","chongqing",["吊脚楼","山城夜色"],"层层叠叠的吊脚楼风格建筑沿崖而建，入夜后的暖色灯光与江面形成鲜明的层次。",["沿江看建筑全貌","灯光倒影","不同高度的城市视角"],"优先从公共步道看全貌，人多时缩短内部停留。","约1小时"),
p("guanyin","观音桥","重庆 · 江北",29.574,106.532,"城市",undefined,["商圈","可选"],"重庆热闹的商圈之一，适合吃饭和感受城市生活。",["商业街区","本地餐饮","夜间街景"],"26日时间紧，这一站作为可选项；不影响晚间去成都。","有余力再去",{optional:true}),
p("eling","鹅岭公园","重庆 · 渝中",29.552,106.525,"公园","eling",["登高看城","园林"],"在山脊上的园林走走，从高处理解重庆两江之间的城市形态。",["园林小径","城市高差","登高视野"],"与鹅岭二厂就近串联，按体力取舍登高项目。","约1小时"),
p("erchang","鹅岭二厂","重庆 · 渝中",29.551,106.532,"街区",undefined,["老厂房","文创街区"],"旧印制厂的建筑肌理保留在坡地街区里，适合随走随拍、找间小店休息。",["旧工业建筑","坡地街巷","咖啡与小店"],"与鹅岭公园安排在同一时段，控制停留时间。","约45—60分钟"),
p("shancheng","山城步道","重庆 · 渝中",29.5506,106.5618,"步行","shancheng",["坡坎","江景","老街"],"顺着山势穿过街巷、台阶与临江步道，用步行感受重庆。",["山城巷一带街景","高低错落的民居","临江视角"],"地图标示山城巷游览范围，步道实际出入口按现场指引。","约1—1.5小时",{source:"https://www.cq.gov.cn/zjcq/ydjs/scbd/"}),
p("shibati","十八梯","重庆 · 渝中",29.5501,106.5702,"街区","shibati",["梯坎街巷","传统风貌"],"石阶沿着山坡连接上下半城，传统风貌建筑、院落与街巷保留着山城生活的空间感。",["石阶与坡地街巷","传统风貌建筑","小店与市井气息"],"穿舒适的鞋，留足取行李和去车站的时间。","约1小时",{source:"https://wap.cq.gov.cn/zwgk/zfxxgkml/zdlyxxgk/ggwh/ly/zxdt/202510/t20251024_15110103.html"}),
p("chengdu","成都","四川 · 成都",30.6598,104.0633,"城市","renmin",["茶馆","城市漫步"],"这次旅行的中转站，也是一整天慢慢逛的目的地。草堂的树影、公园的盖碗茶和太古里的街景，可以各留一点时间。",["27日完整城市游览","川西出发前取车补给","6日自驾返回成都，7日武侯祠与锦里"],"29日晚从九寨沟返抵后直接休息；提前确认取车衔接，30日尽早出城。","9月26—30日 / 10月6—7日",{photoLabel:"成都人民公园实景"}),
p("panda","成都大熊猫基地","四川 · 成都",30.7323,104.1455,"动物","panda",["大熊猫","上午场"],"在竹林与园舍之间寻找大熊猫。把上午留给观察和慢慢走，下午休息、整理行李，晚上前往九寨沟。",["观察大熊猫的日常","竹林园区","上午参观"],"提前预约28日上午场，按高铁时间安排离园；不以看某一只熊猫为必须完成的目标。","28日上午",{source:"https://m.panda.org.cn/cn/"}),
p("chengdudong","成都东站","四川 · 成都",30.6296,104.1408,"交通",undefined,["高铁","九寨沟往返"],"28日晚上从这里乘车前往黄龙九寨站，29日游览九寨沟后返回成都。",["28日晚出发","29日晚回成都","高铁与接驳分段安排"],"往返日期已调整为28日出发、29日返回；班次以调整后的实际订单为准。","按实际车次"),
p("huanglong","黄龙九寨站","四川 · 松潘",32.975,103.604,"交通",undefined,["高铁站","景区接驳"],"这里是高铁与公路接驳的换乘点，距离九寨沟口还需要一段车程。",["接驳前往九寨沟口","出站与上车衔接","回程按车次倒排时间"],"官方参考接驳约2小时，节假日给候车和道路情况留余量。","接驳约2小时",{source:"https://www.jiuzhai.com/news/notice/11241-2026-07-08-03-30-49"}),
p("jiuzhaigou","九寨沟","四川 · 阿坝",33.263,103.919,"湖泊","jiuzhaigou",["彩色海子","瀑布","森林"],"蓝绿相间的湖水、钙华瀑布与山林沿沟谷展开。景区呈Y字形，观光车与栈道相结合，适合把时间留给水色和倒影。",["五花海与熊猫海的水色","诺日朗瀑布","长海、五彩池按当天调度安排"],"28日晚住沟口，29日游览后回成都。先按返程车次确定最晚出沟时间，再决定当天取舍。","29日游览",{source:"https://www.jiuzhai.com/intelligent-service/way-of-play"}),
p("dufu","杜甫草堂","四川 · 成都",30.659,104.025,"人文","dufu",["诗意园林","竹影"],"庭院、竹林、溪水与诗人的故事交织，是成都适合放慢脚步的一处园林。",["茅屋与园林","诗歌文化","竹林和红墙的光影"],"27日上午安排，不必为了拍照走遍每一个角落。","约1.5—2小时"),
p("kuanzhai","宽窄巷子","四川 · 成都",30.669,104.052,"街区","kuanzhai",["院落","老街"],"院落建筑与商业小店组成的步行街区，适合看看建筑、尝点小吃，再走去附近的人民公园。",["院落与砖墙","街头小吃","老街建筑细节"],"作为城市漫步的一段，时间不足时缩短停留。","约1小时"),
p("renmin","人民公园","四川 · 成都",30.6589,104.055,"公园","renmin",["盖碗茶","成都日常"],"找一张竹椅坐下来，喝杯盖碗茶，看公园里的聊天、散步与日常生活。",["茶馆与竹椅","园林散步","放慢节奏"],"把这里当休息的一站，给川西自驾存一点体力。","约1—1.5小时"),
p("chunxi","春熙路","四川 · 成都",30.654,104.078,"城市","taikoo",["步行街","城市夜景"],"成都中心城区的商业步行街，适合晚餐前后走走，与太古里一带串联。",["商业街景","餐饮","附近城市地标"],"27日晚看精力安排，避免太晚回酒店。","晚餐前后",{photoLabel:"成都太古里实景 · 周边街区参考"}),
p("taikoo","太古里","四川 · 成都",30.6516,104.0825,"街区","taikoo",["开放街区","建筑","夜景"],"低层商业建筑、街巷与大慈寺周边空间交织，适合用晚间的一小段时间看看成都的当代街景。",["开放式街巷","现代建筑细节","晚间灯光"],"和春熙路一起安排，时间紧就走一小圈。","约1小时"),
p("wuhou","武侯祠","四川 · 成都",30.6457,104.0484,"人文","wuhou",["三国文化","祠庙园林","红墙竹影"],"走进纪念刘备、诸葛亮与蜀汉人物的祠庙，在院落、碑刻和园林之间了解三国故事。红墙与竹影也适合慢慢看、慢慢拍。",["刘备、诸葛亮与蜀汉人物的历史故事","祠庙建筑、碑刻与园林","红墙夹道和竹影"],"10月7日先游武侯祠，再步行到相邻的锦里。门票预约和入馆时间以官方公布为准。","建议约2—3小时",{source:"https://www.wuhouci.net.cn/",photoLabel:"成都武侯祠实景"}),
p("jinli","锦里","四川 · 成都",30.6452,104.0505,"街区","jinli",["川西街巷","小吃","灯笼"],"紧邻武侯祠的民俗街区，以川西民居风格的建筑串起茶馆、小吃和手工作坊。逛完博物馆后顺路散步，把最后一天留给成都街巷的烟火气。",["川西民居风格的街巷和灯笼","传统小吃、茶馆与手工艺","与武侯祠相邻，可步行串联"],"10月7日接在武侯祠之后，边逛边吃；时间充裕可看傍晚灯光，后续返程另行安排。","建议约1—2小时",{source:"https://www.cdjinli.com/",photoLabel:"成都锦里实景"}),
p("siguniang","四姑娘山 · 双桥沟","四川 · 小金",31.04,102.805,"雪山","siguniang",["雪峰","森林","观光车"],"雪峰、森林、溪流和高山草甸沿沟谷依次展开。以观光车串联停靠点，再在喜欢的地方步行看景。",["红杉林与远处山峰","布达拉峰一带山形","四姑娜措与草甸"],"30日从成都早出发，只游双桥沟，之后还要前往丹巴。","建议约3—4小时",{source:"https://www.sgns.cn/play",altitude:"沟内约2900—3800米"}),
p("danba","丹巴","四川 · 甘孜",30.879,101.884,"藏寨","danba",["河谷","嘉绒文化"],"藏寨沿河谷两侧的山坡分布，白墙、碉楼和田地层叠展开。30日晚在这里落脚，次日上午游览中路藏寨。",["山坡藏寨","传统碉楼","河谷风光"],"住宿可以选县城或便于次日出发的位置。","30日晚住宿",{photoLabel:"丹巴中路藏寨实景"}),
p("zhonglu","中路藏寨","四川 · 丹巴",30.899,101.929,"藏寨","danba",["中路藏寨","古碉","村落"],"古碉、白墙民居与坡地田园相互穿插，更适合边走边看村落日常。",["古碉与民居","层叠田园","山坡小路"],"10月1日只游中路藏寨；自驾定位到村内观景台旁停车点，再步行游览。","约1.5—2小时"),
p("yala","雅拉雪山 · 远眺","四川 · 甘孜",30.725,101.628,"雪山","yala",["沿途观景","短停"],"雪峰从草甸和山谷上方升起，天气通透时轮廓格外鲜明。这次安排沿途远眺，把步行体力留给亚丁。",["雅拉雪山轮廓","草甸与雪山层次","沿途观景"],"地图为丹巴至八美方向的观景范围示意，停车以现场正规观景点为准，不安排入景区徒步。","约20—30分钟"),
p("moshi","墨石公园","四川 · 道孚",30.736,101.553,"地质","moshi",["墨色石林","地貌"],"灰黑色石林与草地形成强烈反差，沿步道走进其中，可以近看岩石的纹理和形态。",["墨色石林","岩石纹理","草地与石林的色彩反差"],"作为1日主要游览点，按栈道和现场指引行走。","约1.5—2小时"),
p("tagong","塔公草原","四川 · 康定",30.322,101.533,"草原","tagong",["草甸","雪山背景"],"开阔草甸与远山相接，藏式建筑和经幡点缀其中，适合在去新都桥途中停下来看看。",["草原视野","雪山背景","藏地风景"],"1日以短停为主，不再追加长时间徒步或骑行。","约30—45分钟"),
p("xinduqiao","新都桥","四川 · 康定",30.036,101.496,"田园","xinduqiao",["光影","藏居","住宿枢纽"],"溪流、草甸、藏居与山坡构成舒展的风景。它也是这段自驾的落脚点，出发去亚丁，再回来探访贡嘎。",["河谷田园","晨昏光影","1日、4日、5日晚住宿"],"秋色随当年天气变化；不要把照片里的颜色当作出行当天的保证。","三晚落脚",{altitude:"镇区约3300—3500米"}),
p("bends","天路十八弯","四川 · 雅江",29.999,100.858,"公路",undefined,["G318","盘山路"],"盘山公路在山坡上层层折返，是从新都桥去理塘途中适合短停的一处公路景观。",["曲折公路线条","高原开阔视野","沿途短暂停留"],"仅在正规观景区停车，不在行车道停车拍摄。","约15—20分钟"),
p("litang","理塘","四川 · 甘孜",29.996,100.27,"高原城镇","litang",["高原城镇","藏地文化"],"群山与高原草地之间的城镇。2日在这里午餐、简单逛逛，随后继续前往香格里拉镇。",["高原城镇街景","藏式建筑","沿途草原"],"这天主要任务是转场，不追加理塘深度游。","午餐与短逛",{altitude:"县城约4000米"}),
p("shangrila","香格里拉镇（日瓦）","四川 · 稻城",28.481,100.289,"城镇",undefined,["亚丁门户","进出景区"],"这里是四川稻城县的香格里拉镇，靠近亚丁景区入口。2日晚住仁村天籁庄园酒店；3日游亚丁后改住景区内亚丁村，4日出沟取车返程。",["景区外住宿","长线前后休息","餐饮与补给"],"订房时确认是稻城县香格里拉镇，不是云南香格里拉市。","2日抵达 / 4日离开",{altitude:"约2900米"}),
p("yading","稻城亚丁","四川 · 稻城",28.439,100.349,"雪山","yading",["三座雪山","高山湖泊","长线徒步"],"雪山、草甸与高山湖泊汇聚在同一片山谷。这次给亚丁长线完整一天，4日不再二进沟。",["洛绒牛场远望雪山","牛奶海与五色海","山谷、草甸与溪流"],"观光车、步行和电瓶车都需要时间；以景区当日开放线路、放行和返程时间为准。","3日完整一天",{source:"https://www.daocheng.gov.cn/dcyw/article/727365",photoLabel:"稻城亚丁实景"}),
p("luorong","洛绒牛场","四川 · 亚丁",28.368,100.363,"草甸","yading",["雪山草甸","长线起点"],"草甸、溪流与雪山在这里相遇，也是判断是否继续长线的合适位置。",["远望雪山","高原草甸与溪流","长线前整理补给"],"如果身体不适或时间不足，在此欣赏风景后返回也是完整的体验。","长线途中",{altitude:"约4150米",photoLabel:"稻城亚丁区域实景"}),
p("gongga","贡嘎措","四川 · 亚丁",28.354,100.35,"湖泊","yading",["长线路段","沿途水景"],"亚丁长线路段中的一站，继续前行需要结合体力、天气与景区放行安排。",["高原水景","山谷步道","长线沿途风景"],"地图位置为线路范围示意，行走以景区标识为准。","长线途中",{photoLabel:"稻城亚丁区域实景"}),
p("milk","牛奶海","四川 · 亚丁",28.353,100.34,"湖泊","yading",["高山湖泊","雪山环抱"],"雪山围合中的高山湖泊，湖水的颜色随着光照和天气变化，是这次长线的重要目的地。",["湖水与雪山同框","高海拔山谷","步道沿途的山势变化"],"按体力和景区规定折返；不为了凑齐景点延误下山。","长线终点区域",{altitude:"约4600米",photoLabel:"稻城亚丁实景"}),
p("five","五色海","四川 · 亚丁",28.356,100.338,"湖泊","yading",["高山湖泊","量力前往"],"位于更高处的湖泊，风景与体力考验一起到来。是否前往取决于当天状态。",["高处湖面","雪山背景","高山地貌"],"洛绒牛场起往返长线官方参考6—8小时，另算景区进出交通。","视体力与开放情况",{altitude:"约4700米",source:"https://www.daocheng.gov.cn/dcyw/article/727365",photoLabel:"稻城亚丁区域实景"}),
p("lengga-a","冷嘎措A线游客中心","四川 · 帮木吉德方向",29.635339,101.701143,"交通",undefined,["已选A线","停车换乘"],"10月5日从新都桥瑞枫民宿出发，沿公路抵达帮木吉德方向的冷嘎措A线游客中心，停好车再上山。",["自驾到游客中心","上山段另行安排","游览后原路方向返回瑞枫民宿"],"道路规划到A线游客中心，不延伸到湖边；实际停车、上山方式与道路通行按当地当天安排确认。","10月5日自驾往返",{source:"https://www.amap.com/place/B0MUZD6JIK"}),
p("lenggacuo","冷嘎措","四川 · 贡嘎西坡",29.586,101.691,"湖泊","lenggacuo",["贡嘎倒影","白天观景","不等日落"],"在高山湖泊前等待云层移动，看贡嘎的轮廓与水面相遇。5日只安排这一站，白天观景、下午下山。",["贡嘎西坡视角","无风时的湖面倒影","雪山与高山湖泊"],"已选A线、帮木吉德方向。自驾到A线游客中心后，上山方式与通行情况临行确认；返程仍住瑞枫民宿，不叠加其他景点。","5日一整天",{altitude:"湖边约4500米",source:"https://www.kangding.gov.cn/xzdt/article/711502",photoLabel:"贡嘎星轨与湖面倒影 · 区域参考，非冷嘎措定位照"}),
p("s434","省道434风景线","四川 · 康定",30.157,101.875,"公路",undefined,["返程备选","沿途风景"],"从新都桥返回康定时，天气和道路条件允许可选择的风景线路。沿途看景以不影响当天回成都为前提。",["高原山地风光","沿途观景","返回康定"],"地图是路线范围示意，出发前核对导航和交管信息。","6日返程途中"),
p("kangding","康定","四川 · 甘孜",30.05,101.96,"城镇",undefined,["返程经过","回成都"],"从川西高原回到成都平原途中经过的城市。6日主要安排返程，按需要停车吃饭、休息。",["山谷城市","返程补给","经雅安回成都"],"10月6日返回成都，7日继续游览武侯祠和锦里。","6日返程途中")
];
export const placeById=Object.fromEntries(places.map(p=>[p.id,p])) as Record<string,Place>;
export type TripDay={startStay?:string;endStay?:string;id:number;date:string;weekday:string;title:string;subtitle:string;stay:string;mode:"flight"|"rail"|"city"|"drive"|"hike";stops:string[];optional?:string[];note:string;parts:{period:string;text:string}[];};
export const days:TripDay[]=[
{id:1,endStay:"hotel-chongqing",date:"09.25",weekday:"周五",title:"南京 → 重庆",subtitle:"山城的第一盏灯",stay:"重庆",mode:"flight",stops:["nanjing","jiangbei","jiefangbei","kuixing","cruise","hongya"],note:"暂按10:15抵达江北机场。魁星楼与解放碑同日游览，夜游码头以船票为准。",parts:[{period:"上午",text:"南京飞重庆，前往市区入住或寄存行李"},{period:"下午",text:"解放碑、魁星楼，午餐与城市漫步"},{period:"晚上",text:"两江夜游、洪崖洞夜景"}]},
{id:2,startStay:"hotel-chongqing",endStay:"hotel-chengdu-west",date:"09.26",weekday:"周六",title:"重庆 → 成都",subtitle:"走过山城的阶梯",stay:"成都",mode:"rail",stops:["eling","erchang","shancheng","shibati","chengdu"],optional:["guanyin"],note:"观音桥有时间再加。给取行李、去车站和进站留足时间。",parts:[{period:"上午",text:"鹅岭公园、鹅岭二厂，按兴趣取舍"},{period:"下午",text:"山城步道、十八梯"},{period:"晚上",text:"高铁前往成都，入住休息"}]},
{id:3,startStay:"hotel-chengdu-west",endStay:"hotel-chengdu-west",date:"09.27",weekday:"周日",title:"成都 · 慢慢逛",subtitle:"竹影、盖碗茶与街巷",stay:"成都",mode:"city",stops:["dufu","kuanzhai","renmin","chunxi","taikoo"],note:"成都市区游览调整到27日。安排补给，提前确认29日返成都后的取车或送车方式。",parts:[{period:"上午",text:"杜甫草堂"},{period:"下午",text:"宽窄巷子、人民公园，坐下来喝杯茶"},{period:"晚上",text:"春熙路、太古里看精力安排"}]},
{id:4,startStay:"hotel-chengdu-west",date:"09.28",weekday:"周一",title:"熊猫基地 → 九寨沟",subtitle:"上午看熊猫，晚上进山",stay:"九寨沟口",mode:"rail",stops:["panda","chengdudong","huanglong","jiuzhaigou"],note:"熊猫基地预约28日上午场，晚上乘高铁及接驳前往九寨沟口；提前衔接夜间接驳和酒店入住。",parts:[{period:"上午",text:"成都大熊猫基地"},{period:"下午",text:"休息、用餐、取行李，按实际车次前往成都东站"},{period:"晚上",text:"高铁至黄龙九寨站，换乘接驳到九寨沟口入住"}]},
{id:5,endStay:"hotel-chengdu-west",date:"09.29",weekday:"周二",title:"九寨沟 → 成都",subtitle:"把一天留给湖水",stay:"成都",mode:"rail",stops:["jiuzhaigou","huanglong","chengdudong"],note:"29日游览九寨沟后当晚返回成都。按调整后的车次倒排出沟、接驳和进站时间；取车衔接提前确认，返抵后尽早休息。",parts:[{period:"上午",text:"尽早入沟，结合观光车调度游览海子与瀑布"},{period:"下午",text:"在返程时间允许范围内继续游览，取行李后接驳去车站"},{period:"晚上",text:"高铁返回成都，按事先安排完成取车或送车衔接后休息"}]},
{id:6,startStay:"hotel-chengdu-west",endStay:"hotel-danba",date:"09.30",weekday:"周三",title:"四姑娘山 → 丹巴",subtitle:"开始向雪山靠近",stay:"丹巴",mode:"drive",stops:["chengdu","siguniang","danba"],note:"川西自驾第一天，只选双桥沟，不叠加其他沟。行车与游览都较满，尽早出发。",parts:[{period:"早晨",text:"成都尽早出发，经映秀、卧龙前往四姑娘山"},{period:"白天",text:"双桥沟观光车与短距离步行游览"},{period:"傍晚",text:"经小金前往丹巴入住"}]},
{id:7,startStay:"hotel-danba",endStay:"hotel-cangrelin",date:"10.01",weekday:"周四",title:"藏寨 → 新都桥",subtitle:"村落、石林与草原",stay:"新都桥",mode:"drive",stops:["danba","zhonglu","yala","moshi","tagong","xinduqiao"],note:"只去中路藏寨；雅拉沿途观景，墨石公园主游，塔公短停。",parts:[{period:"上午",text:"中路藏寨，停车后慢走"},{period:"下午",text:"雅拉沿途观景、墨石公园、塔公草原短停"},{period:"晚上",text:"入住新都桥"}]},
{id:8,startStay:"hotel-cangrelin",endStay:"hotel-tianlai",date:"10.02",weekday:"周五",title:"理塘 → 香格里拉镇",subtitle:"沿着318向南",stay:"香格里拉镇（日瓦）",mode:"drive",stops:["xinduqiao","bends","litang","shangrila"],note:"长途驾驶日：天路十八弯短停，理塘午餐与简单游览。住宿是四川稻城县香格里拉镇。",parts:[{period:"上午",text:"新都桥出发，经雅江、天路十八弯"},{period:"下午",text:"理塘午餐，经稻城前往香格里拉镇"},{period:"晚上",text:"准备亚丁长线补给，早点休息"}]},
{id:9,startStay:"hotel-tianlai",endStay:"hotel-zhaxi",date:"10.03",weekday:"周六",title:"亚丁 · 长线徒步",subtitle:"雪山与海子的约定",stay:"亚丁村 · 扎西空墅",mode:"hike",stops:["shangrila","yading","luorong","gongga","milk","five"],note:"长线按当天身体、天气和景区放行情况取舍，预留所有交通与下山时间。",parts:[{period:"早晨",text:"尽早入园，观光车、步行与电瓶车衔接至洛绒牛场"},{period:"白天",text:"洛绒牛场、贡嘎措，量力前往牛奶海和五色海"},{period:"傍晚",text:"按景区时间返回亚丁村，入住扎西空墅酒店"}]},
{id:10,startStay:"hotel-zhaxi",endStay:"hotel-ruifeng",date:"10.04",weekday:"周日",title:"直接返回新都桥",subtitle:"一路返程，留足休息",stay:"新都桥",mode:"drive",stops:["shangrila","litang","xinduqiao"],note:"已取消亚丁短线：不去冲古寺、珍珠海，不二进沟。两位司机轮换，沿途只作必要休息和短停。",parts:[{period:"早晨",text:"早餐后从亚丁村乘观光车出沟，到游客中心停车场取车出发"},{period:"白天",text:"经稻城、理塘、雅江回新都桥"},{period:"晚上",text:"休息，确认次日冷嘎措A线上山方式与通行情况"}]},
{id:11,startStay:"hotel-ruifeng",endStay:"hotel-ruifeng",date:"10.05",weekday:"周一",title:"冷嘎措 · 贡嘎倒影",subtitle:"白天看山，下午归来",stay:"新都桥",mode:"drive",stops:["xinduqiao","lengga-a","lenggacuo","xinduqiao"],note:"两位司机，不必等日照金山。只游冷嘎措，不追加泉华滩、子梅垭口；天气、体力或通行条件不合适就调整。",parts:[{period:"早晨",text:"瑞枫民宿早出发，前往帮木吉德方向的冷嘎措A线游客中心"},{period:"白天",text:"在A线游客中心停车后按现场安排上山，看贡嘎和湖面倒影"},{period:"下午",text:"按路线倒推下山时间，争取天黑前完成主要山路"}]},
{id:12,startStay:"hotel-ruifeng",endStay:"hotel-chengdu-wuhou",date:"10.06",weekday:"周二",title:"新都桥 → 成都",subtitle:"带着照片回到城市",stay:"成都",mode:"drive",stops:["xinduqiao","s434","kangding","chengdu"],note:"S434按天气与路况决定；当天优先保证回成都，次日安排武侯祠与锦里。",parts:[{period:"上午",text:"从新都桥出发，条件允许时走省道434"},{period:"白天",text:"经康定、雅安返回成都，途中安排休息"},{period:"晚上",text:"抵达成都，还车、入住休息"}]},
{id:13,startStay:"hotel-chengdu-wuhou",date:"10.07",weekday:"周三",title:"武侯祠 → 锦里",subtitle:"三国故事与成都烟火",stay:"成都 / 后续待安排",mode:"city",stops:["wuhou","jinli"],note:"两处相邻，步行串联即可。这天留给成都文化与街巷，后续离开成都的航班或火车尚未安排。",parts:[{period:"上午",text:"武侯祠，看三国文化、祠庙园林与红墙竹影"},{period:"下午",text:"步行到锦里，逛街巷、尝小吃，按兴趣坐茶馆"},{period:"傍晚",text:"有余力可看锦里灯光；后续返程按实际安排"}]}
];
export type RouteLine={day:number;mode:"rail"|"flight"|"walk";coords:[number,number][]};
const coord=(id:string):[number,number]=>[placeById[id].lat,placeById[id].lng];
const byIds=(ids:string[])=>ids.map(coord);
export const routes:RouteLine[]=[
{day:1,mode:"flight",coords:byIds(["nanjing","jiangbei"])},
{day:1,mode:"walk",coords:byIds(["jiefangbei","kuixing","hongya","cruise"])},
{day:2,mode:"walk",coords:byIds(["eling","erchang","shancheng","shibati"])},
{day:2,mode:"rail",coords:[coord("shibati"),[29.59,105.05],coord("chengdu")]},
{day:4,mode:"rail",coords:[coord("chengdudong"),[31.37,103.7],[31.86,103.75],[32.64,103.61],coord("huanglong")]},
{day:5,mode:"rail",coords:[coord("huanglong"),[32.64,103.61],[31.86,103.75],[31.37,103.7],coord("chengdudong")]},
{day:3,mode:"walk",coords:byIds(["dufu","kuanzhai","renmin","chunxi","taikoo"])},
{day:9,mode:"walk",coords:byIds(["luorong","gongga","milk","five","milk","gongga","luorong"])},
{day:13,mode:"walk",coords:byIds(["wuhou","jinli"])}];
export const overviewIds=["hongya","chengdu","panda","jiuzhaigou","siguniang","danba","yala","moshi","tagong","xinduqiao","litang","yading","lenggacuo"];
export const stayName=(day:TripDay)=>day.endStay?placeById[day.endStay].name:day.stay;
export const dayPlaceIds=(day:TripDay)=>Array.from(new Set([...(day.startStay?[day.startStay]:[]),...day.stops,...(day.optional||[]),...(day.endStay?[day.endStay]:[]),...([9,10].includes(day.id)?["yading-parking"]:[])]));
export const modeLabel={flight:"飞机 / 城市漫步",rail:"高铁 / 接驳",city:"城市漫步",drive:"自驾",hike:"高原徒步"};
export const tripDaysFor=(id:string)=>days.filter(d=>dayPlaceIds(d).includes(id));
